### ISSUE TITLE
buyMarket and sellMarket not working!

### ISSUE THREAD

**Issue by SiddharthOX** [abhinavk99/livecoin-api#6] opened 2019-01-22 07:02 UTC
When I am trying to run 

client. buyMarket('BTC', 'USD', 0.5)
  .then(console.log)
  .catch(console.error);

client.sellMarket('BTC', 'USD', 0.5)
  .then(console.log)
  .catch(console.error);

It is showing the following error:

{ success: false,
  added: false,
  orderId: null,
  exception: 'Modifiable Api is not available for you' }
{ success: false,
  added: false,
  orderId: null,
  exception: 'Modifiable Api is not available for you' }

Can you explain me why this following error is coming?

**Comment by abhinavk99** [comment] 2019-01-22 07:08
Hmm that is really weird, the error message you got isn't on the list of possible error messages on https://www.livecoin.net/api?lang=en. Are you sure you did authorization correctly?

**Comment by SiddharthOX** [comment] 2019-01-22 08:28
Yes my authorization is correct. Because when I am running 

client.getAddress('btc').then(console.log);

It is showing the result:
{ fault: null,
  userId: 711983,
  userName: 'sasuke0008',
  currency: 'BTC',
  wallet: '3A3jiix5c5Uzf9BpMH22srviLtc7ZPXVch' }

So what do you think problem is?

**Comment by abhinavk99** [comment] 2019-01-22 21:06
I apologize but I don't really know, I think it's an issue on the end of LiveCoin as it's probably saying that you can't use the API methods that do trades like buyMarket and sellMarket.

**Comment by ghost** [comment] 2019-07-01 14:57
this is not a bug, you have most likely read-only mode on your keypair. 
You need to select `Full` mode and enable trade/payment requests in the two dropdown menus when generating the api key.

**Comment by abhinavk99** [comment] 2019-07-01 15:13
Thanks for the insight!
I think this should help you out @SiddharthOX

**Comment by abhinavk99** [comment] 2019-07-14 16:38
Closing since the one who opened the issue hasn't been active for 6 months and the issue seems to be resolved.

**Closed as completed by abhinavk99** 2019-07-14 16:38 UTC
